name: Build Vue and Deploy Node App

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main     
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:


    - name: Build Vue app
      working-directory: client
      run: |       
        cd ~
        pwd 


        echo '== build end ==='
        
